### ISSUE TITLE
why put gtv3 source

### ISSUE THREAD

**Issue by iProgramMC** [noobes1337/GTPS-Source-Leaks#1]
s

**Comment by noobes1337** [comment]
mad?

**Comment by iProgramMC** [comment]
no, just disappointed @noobes1337

**Comment by noobes1337** [comment]
of what? The cpp is already leaked noone cares now.

**Comment by Jake-png** [comment]
Rip xD

**Comment by cindy498** [comment]
Why no enet and run.py

**Comment by cindy498** [comment]
Im need

**Comment by iProgramMC** [comment]
@noobes1337 I will DMCA strike your GitHub account if you don't remove GTV3.rar from the repository within 48 hours.

**Comment by iProgramMC** [comment]
@noobes1337 28 hours remain

**Comment by noobes1337** [comment]
Actually 26

**Comment by GuckTubeYT** [comment]
bruh noob

**Comment by verticalsync** [comment]
lol you can still download https://raw.githubusercontent.com/noobes1337/GTPS-Source-Leaks/3adacc9a814bea21f530afa608d030b49326905a/GTv3.rar
